### ISSUE TITLE
Assigning Tags

### ISSUE THREAD

**Issue by jaideep11061982** [seewoo5/KT#1]
Hi Seewoo
I find that there are multiple tags assigned to question  meaning related to different lectures.
In the input how are are you taking the tag      if there are multiple tags for a question..

**Comment by seewoo5** [comment]
Actually, my implementation considers only questions but not tags if both are available. (The pre-processed datasets themselves only have two columns - question_id or tag_id & correctness) 
If you want to integrate both features, naive approach is to use two embedding layers for both question ids and tag ids, and you can treat multiple tag cases by averaging or summing out the embedded vectors. There are some works that integrate both features by using graphs, question texts, regularizations, etc.

**Comment by jaideep11061982** [comment]
Thanks for input.. 
in latest paper which is SAINT they consider the   
https://arxiv.org/pdf/2002.07033.pdf

Excercise category as input so i thought if Tag can be used to build one..


Between have you also got any respository for SAINT ?

**Comment by seewoo5** [comment]
Of course it can be used, although the usage may or may not improve the model's performance. I'm not sure when the SAINT's code will be released, but implementation wouldn't be hard if you refer to the harvard's [annotated transformer](https://nlp.seas.harvard.edu/2018/04/03/attention.html) or using `torch.nn.transformer`.
